package car

const ERROR_CAR = 0x16000

const ERROR_CAR_NOT_FOUND_ID = ERROR_CAR + 1

const ERROR_CAR_NOT_FOUND = ERROR_CAR + 2

const ERROR_CAR_PLATENO = ERROR_CAR + 3

const ERROR_CAR_LICENCE_CODE = ERROR_CAR + 4
