package ticket

const ERROR_TICKET = 0x14000

const ERROR_TICKET_NOT_FOUND = ERROR_TICKET + 1

const ERROR_TICKET_NOT_FOUND_SCHEDULE = ERROR_TICKET + 2

const ERROR_TICKET_SCHEDULE_MAX_COUNT = ERROR_TICKET + 3

const ERROR_TICKET_SCHEDULE_USER_MAX_COUNT = ERROR_TICKET + 4

const ERROR_TICKET_SCHEDULE_SEATNO = ERROR_TICKET + 5

const ERROR_TICKET_ORDER_CREATE = ERROR_TICKET + 6

const ERROR_TICKET_NOT_FOUND_LINE = ERROR_TICKET + 7

const ERROR_TICKET_NOT_FOUND_ID = ERROR_TICKET + 8

const ERROR_TICKET_STATUS = ERROR_TICKET + 9
