package driver

const ERROR_DRIVER = 0x15000

const ERROR_DRIVER_PHONE = ERROR_DRIVER + 1

const ERROR_DRIVER_CODE = ERROR_DRIVER + 2

const ERROR_DRIVER_LICENCE_CODE = ERROR_DRIVER + 3

const ERROR_DRIVER_NOT_FOUND_ID = ERROR_DRIVER + 4

const ERROR_DRIVER_NOT_FOUND = ERROR_DRIVER + 5
