package schedule

const ERROR_SCHEDULE = 0x13000

const ERROR_SCHEDULE_NOT_FOUND_LINE_ID = ERROR_SCHEDULE + 1

const ERROR_SCHEDULE_NOT_FOUND_DATE = ERROR_SCHEDULE + 2

const ERROR_SCHEDULE_EXISTS = ERROR_SCHEDULE + 3

const ERROR_SCHEDULE_NOT_FOUND_ID = ERROR_SCHEDULE + 4

const ERROR_SCHEDULE_NOT_FOUND = ERROR_SCHEDULE + 5

const ERROR_SCHEDULE_HAS_PAY = ERROR_SCHEDULE + 6

const ERROR_SCHEDULE_STATUS = ERROR_SCHEDULE + 7

const ERROR_SCHEDULE_MAXCOUNT = ERROR_SCHEDULE + 8

const ERROR_SCHEDULE_UMAXCOUNT = ERROR_SCHEDULE + 9

const ERROR_SCHEDULE_SEATNO = ERROR_SCHEDULE + 10
